name: Build Plugin Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Display version for verification
        run: echo "Building version ${{ env.VERSION }}"
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      
      - name: Create build directory
        run: mkdir -p build/weave-team-members-cpt
      
      - name: Copy plugin files to build directory
        run: |
          rsync -av --exclude='.git' \
                  --exclude='.github' \
                  --exclude='build' \
                  --exclude='.gitignore' \
                  --exclude='.DS_Store' \
                  --exclude='node_modules' \
                  --exclude='package.json' \
                  --exclude='package-lock.json' \
                  --exclude='phpcs.xml' \
                  --exclude='phpunit.xml' \
                  --exclude='tests' \
                  . build/weave-team-members-cpt/
      
      - name: Create zip file
        run: cd build && zip -r weave-team-members-cpt-${{ env.VERSION }}.zip weave-team-members-cpt
      
      - name: List build contents for debugging
        run: ls -la build/
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: build/weave-team-members-cpt-${{ env.VERSION }}.zip
          generate_release_notes: true
